---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tf-serving
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: tf-serving
    spec:
      volumes:
        - name: nfs-volume
          persistentVolumeClaim:
            claimName: nfs
      containers:
      - name: tf-serving
        image: gcr.io/kubeflow-images-public/tf-model-server-cpu:v20180614-f6377404
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 9000
        args:
        - /usr/bin/tensorflow_model_server
        - --port=9000
        - --model_name=test
        - --model_base_path=/tmp/tensorflow/models
        volumeMounts:
          - mountPath: /tmp/tensorflow
            name: nfs-volume
---
apiVersion: v1
kind: Service
metadata:
  name: tf-serving
spec:
  ports:
  - port: 80
    targetPort: 9000
  selector:
    app: tf-serving
